"""pre registiration

Revision ID: aedc2043412e
Revises: 
Create Date: 2026-03-06 15:22:14.973449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedc2043412e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_registirations',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('nes_info', sa.JSON(), nullable=True),
    sa.Column('aygit_company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_pre_registirations_id'), 'pre_registirations', ['id'], unique=False)
    op.create_table('contract_verifications',
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=False),
    sa.Column('verified_code', sa.String(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('pre_registiration_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pre_registiration_id'], ['pre_registirations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_verifications_id'), 'contract_verifications', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('tax_plate', sa.String(), nullable=True),
    sa.Column('other', sa.JSON(), nullable=True),
    sa.Column('pre_registiration_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pre_registiration_id'], ['pre_registirations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('pre_registiration_histories',
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pre_registiration_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pre_registiration_id'], ['pre_registirations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_registiration_histories_id'), 'pre_registiration_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_registiration_histories_id'), table_name='pre_registiration_histories')
    op.drop_table('pre_registiration_histories')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_contract_verifications_id'), table_name='contract_verifications')
    op.drop_table('contract_verifications')
    op.drop_index(op.f('ix_pre_registirations_id'), table_name='pre_registirations')
    op.drop_table('pre_registirations')
    # ### end Alembic commands ###
